version: "3.9"

name: "encryption-demo"

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    ports:
      - 7777:7777
    networks:
      - demo

  vault:
    image: hashicorp/vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    ports:
      - 8200:8200
    networks:
      - demo

volumes:
  db: {}

networks:
  demo: {}
