version: "3.9"

name: "encryption-demo"

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20
    ports:
      - 7777:7777
    networks:
      - demo

volumes:
  db: {}

networks:
  demo: {}
